# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4acef7d6bd5521f0ffc970a26336b1ae51caa95bdd1e6fb767b6689732a6646c4e0ba7cc76eccf013e3b872b6e1125793d4d7db2fec80bc217d0222841632d5

test:
  secret_key_base: 25c87786cee22854f065e8decfe01778c106fe3f9c791bf04a32b3f7597928ac0dab1e91b4998ae4cda46b5a7f456ecd9f5b0eaa45757de4ea2dc941d6c8ca75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
